// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCc4b4XwgymPxoIrxRZ5Hq6cssoOwE09R4',
    appId: '1:569948781438:web:4589524f818a686448d12f',
    messagingSenderId: '569948781438',
    projectId: 'messaging-app-cae4b',
    authDomain: 'messaging-app-cae4b.firebaseapp.com',
    storageBucket: 'messaging-app-cae4b.appspot.com',
    measurementId: 'G-5M9J138GPR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmDAKkYeixAbiYo-XNr-LFEBljQbA75I8',
    appId: '1:569948781438:android:c7f53e0c47ee0a7848d12f',
    messagingSenderId: '569948781438',
    projectId: 'messaging-app-cae4b',
    storageBucket: 'messaging-app-cae4b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKmUorBHcxcBHqXbefPhfp_fDpkZo7MvY',
    appId: '1:569948781438:ios:80b9063a53da9d2a48d12f',
    messagingSenderId: '569948781438',
    projectId: 'messaging-app-cae4b',
    storageBucket: 'messaging-app-cae4b.appspot.com',
    iosBundleId: 'com.example.messagingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKmUorBHcxcBHqXbefPhfp_fDpkZo7MvY',
    appId: '1:569948781438:ios:80b9063a53da9d2a48d12f',
    messagingSenderId: '569948781438',
    projectId: 'messaging-app-cae4b',
    storageBucket: 'messaging-app-cae4b.appspot.com',
    iosBundleId: 'com.example.messagingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCc4b4XwgymPxoIrxRZ5Hq6cssoOwE09R4',
    appId: '1:569948781438:web:a132b31eb19c4f4548d12f',
    messagingSenderId: '569948781438',
    projectId: 'messaging-app-cae4b',
    authDomain: 'messaging-app-cae4b.firebaseapp.com',
    storageBucket: 'messaging-app-cae4b.appspot.com',
    measurementId: 'G-T051TYFYBK',
  );
}
